// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcfnxmtzbgbffwxulkma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjZm54bXR6YmdiZmZ3eHVsa21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2ODUxODMsImV4cCI6MjA1NTI2MTE4M30.37MuVd7GDWwZQWx5c6h5MI7XTdvsYx_L6AKxErL1vo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);